### ISSUE TITLE
Not working on IOS,

### ISSUE THREAD

**Issue by GeekyBharat99** [thuanpham98/processing_camera_image#2]
its not working on IOS, the image is completely grayed and blurred.

**Comment by thuanpham98** [comment]
Can you try againt? I miss flutter for a long time because Covid-19 :(.

**Comment by xurc** [comment]
My app with this plugin does not compile at all for iOS. What am I doing wrong?

![Image](https://github.com/user-attachments/assets/1287daff-1491-4be6-8a7b-d4f27cb044ab)

**Comment by xurc** [comment]
@thuanpham98 
Fixed missing import: 
https://github.com/thuanpham98/processing_camera_image/pull/5

For those who got the same error, here is a temporary solution:
```
dependency_overrides:
  processing_camera_image:
    git:
      url: https://github.com/xurc/processing_camera_image.git
      ref: fix/missing_include_uint
```
